### ISSUE TITLE
Mintomic on arm64

### ISSUE THREAD

**Issue by pellicus** [mintomic/mintomic#11]
Hey there,
i'm trying to run mintomic on amr64 (iphone5s) ... i'm missing something?
in "platform_detect.h"
I got  #error Unrecognized target CPU!
and of course if add 
#elif defined(__arm__) || defined (__arm64)
i got 
 #error Unrecognized ARM CPU architecture version!

I'll try to add another if 
in order to define 
  #define MINT_CPU_ARM_VERSION 8
  #define MINT_PTR_SIZE 8

but i don't have any chance to know if it will works properly :)

Thank you for your reply in advance :D

**Comment by mulle-nat** [comment]
:+1: In general in would be nice to know, what the future of mintomic is. I think I started using mintomic in march, and as my luck would have it started to stale right from there :(

I put this into platform_detect.h

```c
    #elif defined( __arm64__)
        // ARM
        #define MINT_CPU_ARM  1
        #define MINT_PTR_SIZE 8

        #if defined(__ARM64_ARCH_8__)
            // ARMv7
            #define MINT_CPU_ARM_VERSION 8
        #else
            // Could support earlier ARM versions at some point using compiler barriers and swp instruction
            #error Unrecognized ARM CPU architecture version!
        #endif
        #if defined(__thumb__)
            // Thumb instruction set mode
            #define MINT_CPU_ARM_THUMB 1
        #endif
```
But it doesn't compile.

**Comment by preshing** [comment]
If anyone succeeds in adding ARM64 support, I'd merge it!

In the meantime, C11 and C++11 are a lot more ubiquitous now than they were when I started Mintomic... I'm curious, what prevents you from using those?

**Comment by mulle-nat** [comment]
Good to know that C11 (I don't do C++)  support is coming together. Last time I checked around for atomic operations, and that's admittedly a year ago, Xcode 6, did know about C11 but not about `<stdatomic>`. Apparently (having just googled this) it's [C11 support is still only partial](https://forums.developer.apple.com/thread/15070). But you are right, if mintomic is basically staling, I should migrate now. Quite frankly I also always assumed that <stdatomic> isn't inlining, but I just checked it, and at least with clang it does inline.

I did like mintomic and your articles though and used in successfully in my [ABA solution](http://www.mulle-kybernetik.com/weblog/2015/mulle_aba_release.html). So thanks for all the fish ;)

**Comment by pellicus** [comment]
"I'm curious, what prevents you from using those?"

Because using mintomic we know what's under the hood :D.

so do I've to give up about arm64?

thanks anyway.

**Comment by preshing** [comment]
Hi guys, as I mentioned elsewhere, Mintomic is nearing the end of its life. I've basically moved all the atomic C code to Turf: https://github.com/preshing/turf/tree/master/turf/c

I won't make any promises, but native ARM64 support is somewhat more likely to happen there!
