### ISSUE TITLE
can't compile on xcode 6.2 for ios/arm

### ISSUE THREAD

**Issue by pellicus** [mintomic/mintomic#12]
Hey there! :D 

I got some trouble compiling mintomic on xcode 6.2,
in the osx case i had to write a #define asm __asm__ wherever mintomic uses asm volatile ()
and on ios/arm 
I got 
<inline asm>:5:12: error: invalid operand for instruction
   mov     r2, r0
           ^
<inline asm>:7:21: error: register expected
   ldrexd  r0, r1, [r2]
                    ^
<inline asm>:8:25: error: register expected
   strexd  r3, r0, r1, [r2]
etc...

compiling mintomic_gcc.c
so using clang with -arch arm64

I'm missing something :( please give me a direction!

thank you for your time

Dario

**Comment by preshing** [comment]
Hi pellicus, Mintomic is nearing the end of its life. I've basically moved all the atomic C code to Turf: https://github.com/preshing/turf/tree/master/turf/c

See if you encounter any build issues there.
