### ISSUE TITLE
ARMv4/v5 Support

### ISSUE THREAD

**Issue by awm** [mintomic/mintomic#13]
I am interested in adding support for the ARMv4 and ARMv5 instruction sets, since platforms using processors with these ISAs are often using older Linux + GCC environments and lack the various GCC `__sync` intrinsics.  I've given a bit of thought to how I could implement the various operations using the SWP instruction and compiler or kernel memory barriers, but there are some issues with the approach I have been considering.  The following is an example of a SWP-based semaphore implementation of `mint_compare_exchange_strong_32_relaxed` (other functions could be implemented in a similar manner):

```c
uint32_t mint_compare_exchange_strong_32_relaxed(mint_atomic32_t *object, uint32_t expected, uint32_t desired)
{
    uint32_t status;
    uint32_t original;

    asm volatile("       mov     %0, #1\n"
                 "1:     swp     %0, %0, [%3]\n"
                 "       cmp     %0, #1\n"
                 "       beq     1b\n"
                 "       ldr     %1, [%4]\n"
                 "       cmp     %1, %5\n"
                 "       streq   %6, [%4]\n"
                 "       mov     %0, #0\n"
                 "       swp     %0, %0, [%3]\n"
                 : "=&r"(status), "=&r"(original), "+Qo"(object->_nonatomic)
                 : "r"(...sem...), "r"(object), "Ir"(expected), "r"(desired)
                 : "cc");
    return original;
}
```
Note that the `...sem...` refers to some global location to be used as a semaphore for protecting the atomic operation.  The problems I foresee are that:

1. This is not really lock-free anymore due to the reliance on a global semaphore.
2. Using one semaphore for everything would cause unnecessary waiting.
3. Locating and accessing the global semaphore would be difficult.  If the atomics were being used in both an executable and a shared library that was loaded at runtime, then they would likely be using different semaphores even if they shared an address space.

I am willing to work on an implementation of this, but if anyone has any recommendations for approaching the problem I would be grateful.  My test platform is currently an Atmel AT91SAM9XE512 (ARMv5TEJ) and the compiler is GCC 4.2.2 targeting ARMv4T.

**Comment by preshing** [comment]
You're right that it won't be lock-free anymore. It's impossible to make most operations lock-free in userspace on those ISAs.

It's also true that shared libraries will use a different locks, but that's OK.

For a few additional instructions, another option you have is to perform lock striping instead of having a single global lock (or semaphore, as you call it). If the application makes heavy use of separate atomic variables, this *might* reduce the amount of unnecessary spinning when threads are interrupted mid-operation. Something like this:

    #define MINT_GLOBAL_STRIPED_SPINLOCK_COUNT 1024   // or some number

    extern uint32_t mint_globalStripedSpinLocks[MINT_GLOBAL_STRIPED_SPINLOCK_COUNT];

    MINT_C_INLINE uint32_t *mint_acquireGlobalSpinLock(void *object)
    {
        uint32_t lockIndex;
        uint32_t *lock;
        uint32_t temp;
        // Hash the object address to come up with a lock index
        // (Experiment with this hash function)
        lockIndex = ((size_t) object >> 4) & (MINT_GLOBAL_STRIPED_SPINLOCK_COUNT - 1);
        lock = mint_globalStripedSpinLocks + lockIndex;
        asm volatile("       mov     %0, #1\n"
                     "1:     swp     %0, %0, [%1]\n"
                     "       cmp     %0, #1\n"
                     "       beq     1b\n"
                     : "=&r"(temp),
                     : "r"(lock),
                     : "cc", "memory");
        return lock;
    }

    MINT_C_INLINE void mint_releaseGlobalSpinLock(void *lock)
    {
        uint32_t temp;
        asm volatile("       mov     %0, #0\n"
                     "       str     %0, [%1]\n"
                     : "=&r"(temp),
                     : "r"(lock)),
                     : "memory");
    );

    MINT_C_INLINE uint32_t mint_compare_exchange_strong_32_relaxed(mint_atomic32_t *object, uint32_t expected, uint32_t desired)
    {
        uint32_t *lock;
        uint32_t original;
        lock = mint_acquireGlobalSpinLock(object);
        original = *object;
        if (original == expected)
            *object = desired;
        mint_releaseGlobalSpinLock(lock);
        return original;
    }

    MINT_C_INLINE uint32_t mint_fetch_add_32_relaxed(mint_atomic32_t *object, int32_t operand)
    {
        uint32_t *lock;
        uint32_t original;
        lock = mint_acquireGlobalSpinLock(object);
        original = *object;
        *object = original + 1;
        mint_releaseGlobalSpinLock(lock);
        return original;
    }

    ...

This code is untested, so it's possible I made a mistake, but hopefully you see the idea.

If you split the acquire/releaseGlobalSpinLock into separate functions, as is done here, all your asm can go there. The other functions can be implemented in plain C. The asm blocks need to specify "memory" to prevent the compiler from reordering them around the critical sections they're meant to protect.

If you prefer to write them as giant asm blocks instead, that's fine too (just a bigger headache in my opinion), and you don't need "memory" in that case. However, note that your second `swp` can just be a `str`.

Finally, since there are no multicore/multiprocessor ARMv4/v5 implementations (I think?), the only cause of memory reordering is the compiler, and therefore all the fences can be implemented as compiler barriers.

    #define mint_thread_fence_consume() (0)
    #define mint_thread_fence_acquire() asm volatile("" ::: "memory")
    #define mint_thread_fence_release() asm volatile("" ::: "memory")
    #define mint_thread_fence_seq_cst() asm volatile("" ::: "memory")

**Comment by awm** [comment]
Thanks for getting me started, your approach makes sense to me.  I tried running several fairly minimal hash functions on large numbers of generated addresses with properties similar to the static, stack, and heap variables that are likely to be encountered.  The "shift-4" that you used above actually provides quite uniform and fast results, so I'll probably stick with that at least until I have something I can test out on the actual hardware.

Regarding shared libraries, wouldn't there be a problem if, for example, a supposedly atomic variable were being accessed by a thread in the main executable and by a thread in a library loaded by that executable (since the spinlocks would be different)?  It's probably not a particularly common use-case, but I could see one module passing a reference to some structure that contained an atomic variable to another module.

**Comment by preshing** [comment]
You're right. That would be a problem. Is there some way you could put these functions, and `mint_globalStripedSpinLocks`, into their own shared library when compiling mintomic for a shared library?

(I actually just checked what C++11 does when compiling for ARMv5 using `objdump -d`. It relies on the `__sync` functions, which have implementations that are linked into the ELF, which, in turn, seem to rely on a CAS function that is not linked into the ELF. I assume that CAS function exists in a shared library. They jump to the CAS function indirectly via patch table. I'm not exactly sure how the patch table gets initialized. I guess that's the loader's job.)

**Comment by preshing** [comment]
Hi awm, Mintomic is nearing the end of its life.
For my purposes, I've basically moved all the atomic C code to Turf: https://github.com/preshing/turf/tree/master/turf/c
You are welcome to add ARMv4/5 support there if it interests you!
