### ISSUE TITLE
Questions about the implementation

### ISSUE THREAD

**Issue by mzer0-yu** [mintomic/mintomic#17]
After reading [the blog by Preshing](http://preshing.com/20130505/introducing-mintomic-a-small-portable-lock-free-api/) I am still confused about something.
> The C++11 atomic library standard does not guarantee an efficient implementation, only a correct one.

No offense. Why can you provide a better implementation against the compiler? Mintomic's interfaces and compilers' are totally same, it is impossible to have a better implementation without changing the interfaces.

**Comment by mulle-nat** [comment]
Well he can, if the C11 atomic library is not efficiently implemented. Just as it says. Think of it of being mostly academic.

**Comment by mzer0-yu** [comment]
@mulle-nat I had a glance on its implementation, but not sure if it has a big different with the "popular" implementation. If system level locks are not involved with the atomics(i.e. x86, ARM, etc.), is it nothing different with atomics provided by compilers?

**Comment by mulle-nat** [comment]
I think Preshing would agree with you on that: [https://github.com/mintomic/mintomic/issues/11](url). I use **mintomic** as a fallback, when I don't have C11 available

**Comment by mzer0-yu** [comment]
@mulle-nat 

C11 is not available in the latest Visual Studio 2015 yet, so far I have to use the C++11's atomics instead of C11's, but I am wondering if I can make a recap of C++11's atomics into pure C. For example, providing pure C header files as well as C++ source files(compiled to library), then we can have it!

**Comment by mzer0-yu** [comment]
@mulle-nat See you in 10 hours, it is really late in China(12:30 AM). I am interesting in Mintomics. Because stdatomics is not available in Visual Studio, an alternative is to use Mintomics or pure C header files with C++ implementation in source which I mentioned in context. #11 told ARM64 is not supported in Mintomics, so it is not a good choose to use Mintomics for all platforms. Maybe I am wrong about stdatomics, I googled it but found no explanation about it. But Visual Studio does provide a xatomic.h I don't know if it works.

**Comment by mulle-nat** [comment]
Yeah, that ARM64 doesn't work is not so great. Someone recommended [concurrencykit](http://concurrencykit.org) to me, but I haven't checked it out

**Comment by preshing** [comment]
> Why can you provide a better implementation against the compiler?

Back when std::atomic was first added to Visual Studio 2012, it generated pretty bad code (at least in my own testing). It's part of the reason I started Mintomic.

These days, modern compilers do an excellent job with std::atomic in C++11. I would not claim Mintomic is better, only equal.

I haven't really spent time with C11, so I can't comment on that.

**Comment by mzer0-yu** [comment]
@preshing Thanks, I read your blogs a lot and appreciate it. By the way, even if the latest VS 2015 we don't have stdatomic.h available yet, but xatomic.h as well as customized APIs for Win.

**Comment by mzer0-yu** [comment]
@preshing I think I shouldn't ask you questions here, but still do it: why we don't have a StoreLoad barrier but memory_order_seq_cst(it promise more things)?

**Comment by preshing** [comment]
A StoreLoad fence is quite slow in hardware, so the CPU instructions that do it also tend to provide the other fence types too.

**Comment by mzer0-yu** [comment]
@preshing I don't totally understand. When CPU does only a full-barrier, it ensures all intrinsics are sent in program sequence. If we want a sequentially consistent, the CPU does the same and must wait until the memory or all the caches are updated. In my imagination, it must be more costly than a full-barrier. Besides, I think StoreLoad is expensive because Store is always slower than Load, if we force CPU to complete a Store, it must be a longer pipeline stall, am I right?

**Comment by preshing** [comment]
Are you asking about sequentially consistent fences, such as std::atomic_thread_fence(std::memory_order_seq_cst)?

Or are you asking about sequentially consistent loads and stores, such as std::atomic<*>::store(*, std::memory_order_seq_cst)?

They're different things. The comment I wrote about was talking about sequentially consistent fences. But now it sounds like you're trying to figure out how CPUs implement sequentially consistent loads/stores.

**Comment by mzer0-yu** [comment]
@preshing 
Oops......took a mistake, sorry. I think the questions is becoming two subquestions:

1) Why don't we have full-barrier version Load/Store?
2) Why don't we have full-barrier fence?

If I understand right, you answered 2) and told the full-barrier fence will not much cheaper than sequentially consistent fence, so CPU rather provides the second one but not only the first one. I am not an expert of this field, please excuse for my simple mistakes. I think:

a) Modern multi-core CPUs can always ensure memory/caches synchronization in single CPU.
b) MESI protocol is powerful enough to make sure the expense of memory/caches synchronization between CPUs is not such expensive.

So, "CPU rather provides the second one but not only the first one.". And we always use memory fences to achieve well-ordered Load/Store, so it makes no difference in many CPUs between sequentially consistent fences and sequentially consistent Load/Store.

**Comment by mzer0-yu** [comment]
In addition: I mean the full-barrier by LoadLoad+StoreStore+LoadStore+StoreLoad.

**Comment by preshing** [comment]
Sequentially consistent loads and stores are a bit less expensive, though. They don't always need fences. For example, on x86, a sequentially consistent load is implemented as a simple MOV instruction. No explicit CPU fence of any kind. And it works. See http://preshing.com/20120930/weak-vs-strong-memory-models/

See also https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html

**Comment by mzer0-yu** [comment]
@preshing I have read that blog, and learning the link below now. But still curious, what's the costs between LoadLoad+StoreStore+LoadStore+StoreLoad and sequentially consistent? In other word, assuming there are two sets A={LoadLoad+StoreStore+LoadStore+StoreLoad}, B={sequentially consistent}, what scenarios are included in {A-B}? Such like MESI fails, or, even if using Acquire/Release, do we always have {A-B} (means all memory/caches are synchronized)?

**Comment by preshing** [comment]
Sorry, I'm not able to answer your question.

As for atomics in C, I've basically moved all the Mintomic code to Turf, so I encourage you to keep an eye on this subfolder to see if it fits your needs: https://github.com/preshing/turf/tree/master/turf/c
