### ISSUE TITLE
Question: Can I put Atomic types on the heap?

### ISSUE THREAD

**Issue by blakesmith** [mintomic/mintomic#9]
Hello there,

I'm considering using mintomic for a project, and read the following line on the website:

"You should not declare local variables using these atomic types because some compilers do not correctly align local variables on the stack."

The examples I saw in the test suite declare mintomic types as static. I would like to put a mintomic 64 bit integer inside another struct to use as a counter. Will allocating the struct on the heap and doing increments / gets on the atomic type yield correct results under multithreaded contention, or will I see write tearing?

Something like this:

```c
typedef struct my_struct {
  mint_atomic64_t counter;
} my_struct;

void foo() {
  my_struct *s = malloc(sizeof(my_struct));
  // increment the atomic type inside the struct
  free(s);
}
```

Thanks so much!

Blake

**Comment by preshing** [comment]
If you need to use 64-bit atomics in a 32-bit application and you don't have the source code for malloc(), you should probably use memalign() to be safe. The standard only mandates 32-bit-aligned return values from malloc() in a 32-bit application, according to http://stackoverflow.com/a/6389151.

In practice. I've never seen malloc return pointers that were aligned to less than 8 bytes. Doesn't mean it's impossible, just that I haven't seen it.
